name: Build, Test, and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_NUMBER: ${{ github.run_number }}
  VERSION_NAME: 1.0.${{ github.run_number }}

permissions:
  contents: write

jobs:
  build:
    name: IntelliJ Plugin Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle Build Action
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-overwrite-existing: true

      - name: Set Environment Variables
        run: |
          echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
          echo "VERSION_NAME=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Get Plugin Version
        id: plugin_version
        run: echo "VERSION=${{ env.VERSION_NAME }}" >> $GITHUB_ENV

      - name: Create GitHub Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION_NAME }}
          name: Release v${{ env.VERSION_NAME }}
          body: "Automated release for build ${{ env.VERSION_NAME }}"
          draft: false
          prerelease: false
          files: build/distributions/*.zip
